### ISSUE TITLE
Provide configuration options for how log messages are printed

### ISSUE THREAD

**Issue by RyanGlScott** [yav/simple-smt#26]
Currently, SMT solver interactions are logged in a format that looks like this:

```
[send->] (set-option :print-success true )
[<-recv] success
[send->] (set-option :produce-models true )
[<-recv] success
[send->] (set-option :global-decls false )
[<-recv] success
[send->] (declare-datatypes () ((InfNat (mk-infnat (value Int ) (isFin Bool ) (isErr Bool ) ) ) ) )
[<-recv] success
...
```

This is fine for a human looking at the trace of SMT solver queries, but it is less ideal for replaying the SMT solver session. This is because you can't just pass the log file to an SMT solver, as the `[send->] ` and `[<-recv] ` prefixes prevent the logs from parsing as valid SMT queries. Currently, I have to work around this by manually scrubbing out the `[send-> ]` prefixes and removing the `[<-recv] ` lines entirely, which is rather tedious.

Ideally, it would print in a form that looks more like:

```
(set-option :print-success true )
; success
(set-option :produce-models true )
; success
(set-option :global-decls false )
; success
(declare-datatypes () ((InfNat (mk-infnat (value Int ) (isFin Bool ) (isErr Bool ) ) ) ) )
; success
```

This way, I could pass the log file directly to an SMT solver. That being said, it may be preferable to have the other style of log message in different scenarios.

To account for both of these use cases, I propose that we add a `newSolverWithConfig` function and define the existing `newSolver`/`newSolverNotify` functions in terms of it:

```hs
newSolverWithConfig :: Config -> IO Solver
```

What should go into the new `Config` data type? At a minimum, it should include all of the configurable arguments that you can pass to `newSolver`/`newSolverNotify`. It should also include a way to fine-tune the logged output. One possible way to do this would be this:

```hs
data Config = Config
  { solverExecutable :: String
  , solverArguments :: [String]
  , solverOnExit :: Maybe (ExitCode -> IO ())
  , logger :: Maybe Logger
  , loggerSendHerald :: String
  , loggerRecvHerald :: String
  , loggerStderrHerald :: String
  , loggerExceptionHerald :: String
  }
```

By default, `loggerSendHerald` would be `[send->] `, `loggerRecvHerald` would be `[<-recv] `, and so on. Each of the `*Herald` values would be printed in front of each type of message that is logged (send messages, recv messages, and so on). A user could override these options if they wanted to, however. For my needs, I would define `loggerSendHerald = ""` and `loggerRecvHerald = "; "`, which would achieve the output I envision above.

**Comment by yav** [comment]
I wonder if we should go even high-level, and instead of providing a `Maybe Logger` and the hearlads we provide something like this:
```haskell
data SolverLogger = SolverLogger
  { logSend :: SEXpr -> IO ()
  , logRecv :: SExpr -> IO ()
  , logExcn :: IOException -> IO ()
  , logStdErr :: [String] -> IO ()
  }
```
and we can replace the calls to `info` with the corresponding methods.  Then a user of the library has full control over what they want to see:
   * if they want no logging they can provide a values that ignore the arguments and do nothing
   * if they do logging, they can use the `Logger` provided by `SimpleSMT` or some other system.

For convenience we should probably provide a few pre-build ones, for "no logging", "the current behavior", and the new functionality we want ("log for sending back to the logger, so no non-SMT stuff)

**Comment by RyanGlScott** [comment]
What is the relationship between the existing `Logger`  data type and your proposed `SolverLogger`? It's not obvious how `logSend` should interact with the existing [`logMessage`](https://github.com/yav/simple-smt/blob/7243b47100f1be01918e63ead0fb90c3b2a602ff/SimpleSMT.hs#L1012) field, whether `logSend` should take the [`logLevel`](https://github.com/yav/simple-smt/blob/7243b47100f1be01918e63ead0fb90c3b2a602ff/SimpleSMT.hs#L1015) into account, and so on.

**Comment by RyanGlScott** [comment]
Sorry, I'm still not following. If I understand what you are saying correctly, you are proposing that we do something like this:

```hs
data Config = Config
  { solverExecutable :: String
  , solverArguments :: [String]
  , solverOnExit :: Maybe (ExitCode -> IO ())
  , solverLogger :: Maybe SolverLogger
  }

data SolverLogger = SolverLogger
  { solverLogSend :: SExpr -> IO ()
  , solverLogRecv :: SExpr -> IO ()
  , solverLogExcn :: X.IOException -> IO ()
  , solverLogStdErr :: String -> IO ()
  }

defaultSolverLogger :: SolverLogger
defaultSolverLogger = SolverLogger
  { solverLogSend = \_ -> putStr "[send->] "
  , solverLogRecv = \_ -> putStr "[<-recv] "
  , solverLogExcn = \_ -> pure ()
  , solverLogStdErr = \_ -> putStr "[stderr] "
  }
```

Is that correct so far? If so, how would you envision turning a `Logger` into a `SolverLogger`? The best that I could come up with is:

```hs
loggerToSolverLogger :: Logger -> SolverLogger
loggerToSolverLogger l = SolverLogger
  { solverLogSend = \c ->
      do solverLogSend sl c
         logMessage l $ showsSExpr c ""
  , solverLogRecv = \c ->
      do solverLogRecv sl c
         logMessage l $ showsSExpr c ""
  , solverLogExcn = \exc ->
      do solverLogExcn sl exc
         logMessage l $ show exc
  , solverLogStdErr = \errs ->
      do solverLogStdErr sl errs
         logMessage l errs
  }
  where
    sl = defaultSolverLogger

newSolver :: String       {- ^ Executable -}            ->
             [String]     {- ^ Arguments -}             ->
             Maybe Logger {- ^ Optional logging here -} ->
             IO Solver
newSolver exe opts mbLog = newSolverWithConfig $
  (defaultConfig exe opts)
    { solverLogger = loggerToSolverLogger <$> mbLog
    }
```

But this still doesn't feel quite right, however. Let's focus on the implementation of `solverLogSend` in `loggerToSolverLogger`:

```hs
loggerToSolverLogger l = SolverLogger
  { solverLogSend = \c ->
      do solverLogSend sl c
         logMessage l $ showsSExpr c ""
  , ...
  }
```

But this calls `solverLogSend` completely independently of `logMessage`. If the `logMessage` is configured to only print things at a certain `logLevel`, then `solverLogSend` will be completely unaware of this.
```

**Comment by yav** [comment]
I think we don't need a `Maybe` in `solverLogger` and we can use this instead:
```haskell
noLogger :: SolverLogger
noLogger = SolverLogger { solverLogSend = \_ -> pure (), ... etc }
```

To log to an existing logger with the current format, we'd have:
```haskell
defaultLoggerTo :: Logger -> SolverLoger
defaultLoggerTo l = { solverLogSend = \sexp -> logMessage l ("[send ->] " ++ showsSExpr sexp "", ... }
```

One could also define versions that print to `stdout` directly like you did, but I am not sure that we need to.

The logger from the top of the ticket could look like:
```haskell
logInSMT :: Logger -> SolverLogger
logInSMT l = { solverLogSend = \sexp -> logMessage l (showsSExpr sexp ""), solverLogRecv = \sexp -> logMessage l ("; " ++ showsSExpr sexpr ""), ... }
```

I don't have a particularly strong preference on how exactly we do it, I just suggested this because I looked at the 4 places where the solver actually does logging and abstracted over them.
